language: perl
install:
  - sudo apt-get install vim
  - cpanm --notest Test::Differences Text::VimColor IO::Pty Test::Deep Parallel::ForkManager JSON Path::Tiny Test::SharedFork Test::LongString
  - git fetch origin p5-corpus-ng:origin/p5-corpus-ng
  - vim --version
script:
  - make test
perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"
branches:
  except:
    - p5-corpus
